version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=7y7qg5rpq
      - MONGODB_DATABASE=minhahorta
    volumes:
      - ./data:/data/db
